
export const LOAD_SESSION_DATA = 'ui/LOAD_SESSION_DATA';
export const LOAD_SESSION_DATA_COMPLETE = 'ui/LOAD_SESSION_DATA_COMPLETE';
export const STOP_SESSION_RELOAD_ANIMATION = 'ui/STOP_SESSION_RELOAD_ANIMATION';
export const CLOSE_LAUNCH_FAILED_MODAL = 'ui/CLOSE_LAUNCH_FAILED_MODAL ';
